CREATE  TABLE meals(
	id 	INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(180) NOT NULL,
	price FLOAT(11,3) NOT NULL,
	avatar_url VARCHAR(512),
	user_id VARCHAR(90) NOT NULL,
	meal_type ENUM ("A_LA_CARTE","PRE_MADE") NOT NULL,
	date_added TIMESTAMP NOT NULL DEFAULT NOW(),
	UNIQUE(name,user_id),
	CONSTRAINT fk_users_meals FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;